# @package _global_

defaults:
  - _self_
  - data: bigearth # choose datamodule with `test_dataloader()` for evaluation
  - model: pyramid_vae
  - callbacks: callback_test
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}train/runs/2024-01-10_20-44-16/checkpoints/epoch_018.ckpt
